services:
  - type: web
    name: leboncoin-scraper-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: ZYTE_PROXY_URL
        sync: false  # Set this manually in Render dashboard
